### ISSUE TITLE
Complete "Framework" Table for Tech Stack Comparison

### ISSUE THREAD

**Issue by MrM21632** [GE-MDS-FNM-V2/GE-MDS-FNM-V2#31]
Electron, NW.js, Spring, and Cordova

**Comment by MrM21632** [comment]
@danielkjones I think the table is complete. Can you look over it for me and let me know if there's anything we need to add/elaborate on?

**Comment by MrM21632** [comment]
Reopening due to additional changes that @danielkjones needs to make, per David's request.

**Comment by danielkjones** [comment]
Added PWA to table with scores.
