### ISSUE TITLE
Documentation of Anticipated Procedure for Auto-Config UI

### ISSUE THREAD

**Issue by danielkjones** [GE-MDS-FNM-V2/GE-MDS-FNM-V2#41]
Reusable and Auto-configuration of the UI was a project requirement.

We need a plan (sequence diagrams, use cases, misc. models) for how this is going to work.

**Comment by bobrown101** [comment]
**Definition of what we mean by an auto-configurable UI:**

There are multiple radio types, all with different properties and configuration options. For example Radio X may have properties A,B,C and Radio Y may have properties 1,2,3,4. 

We would like our application to be able to auto-generate the correct user interface to allow for configuration for any type of radio. Meaning a user can plug in Radio X and they will be displayed inputs for properties A,B,C, and then a user can unplug Radio X and plug in Radio Y and be given inputs for properties 1,2,3,4.

**Ticket Requirements**
Research and deliver diagrams and/or prototypes on a proposed architecture to allow us to generate a auto-configurable UI based on properties from the MDS radio it is communicating with.

**Deliverables**
- diagrams that have been approved by the team and sponsor (doesnt matter what kind - whatever you think is most effective in portraying your thoughts)
