### ISSUE TITLE
Create UI from wireframes for View Devices

### ISSUE THREAD

**Issue by danielkjones** [GE-MDS-FNM-V2/GE-MDS-FNM-V2#42]
Code up the wire frames from "View Devices From  File" use case.

**Comment by MrM21632** [comment]
This will most certainly require whoever is tasked with this familiarizing themselves with the current application, so that they know what functionality needs to/should be carried over into the new design.

**Comment by bobrown101** [comment]
The deliverable of this ticket is going to me two prototypes demonstrating two different layout designs for this application. It can be technology agnostic - interactive wireframes, react code, pencil and paper - whatever is easier for the assignee.

If there is only one logical layout, at least attempt to create a second, however it is okay to make it much less polished.

**Comment by MrM21632** [comment]
I'll be designing prototypes for the UI. I'll try to familiarize myself with the UI of the existing app as much as possible. There will likely be a lot of stuff we want to transfer to the new interface.

I'll also be sure to communicate with @MattThyng about YANG models as needed.
