### ISSUE TITLE
Basic Web to Radio Communication

### ISSUE THREAD

**Issue by danielkjones** [GE-MDS-FNM-V2/GE-MDS-FNM-V2#44]
We need to demo the reusable nature of a React application that can communicate with a radio using JSON-RPC over IP.

**Comment by bobrown101** [comment]
The deliverable for this ticket is to write a react web application that can be hosted on a local development machine that can communicate over IP to an MDS radio.

The extent of this application shall be a button that the user clicks and triggers an http call to the radio, and dumps the json response into a textbox on the page.
