### ISSUE TITLE
Formal Write-up for Use Cases

### ISSUE THREAD

**Issue by MrM21632** [GE-MDS-FNM-V2/GE-MDS-FNM-V2#54]
Create a formal description and detailed overview for each of the use cases we covered in the last meeting (as of writing this issue):

* View Configured Devices
* View Logs

**Comment by MrM21632** [comment]
Have these ready for next Tuesday's meeting. Once these are done, the team plans to collaborate on the remaining use cases to formally document them.

**Comment by MrM21632** [comment]
At minimum, have the use cases with wireframes ready for next Tuesday's meeting.

**Comment by MrM21632** [comment]
Once these are done, start working on the remaining use cases.

**Comment by danielkjones** [comment]
I'm going to go back and make some adjustments after team feedback.
