### ISSUE TITLE
Research extent of command line interface with device

### ISSUE THREAD

**Issue by MattThyng** [GE-MDS-FNM-V2/GE-MDS-FNM-V2#6]
What can the command line do and not do?

**Comment by MattThyng** [comment]
Due 9/29/2019

**Comment by davidchristine88** [comment]
Just a few notes about command line - some features or interfaces (ex: WEB UI JSONRPC), has to be enabled via command-line before they can function.  Also our factory use command-line only to perform firmware upgrade, security provisioning, and basic device configuration.
